### ISSUE TITLE
Render Data into a Graph

### ISSUE THREAD

**Issue by maxmellen** [KpitaineSoftware/kpitaine#21]

**Comment by margauxbais** [comment]
@maxmellen si cela peut t'aider, j'avais gardé la liste de nos recherches de graph (lors de notre premier workshop) : 
- https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware
- https://github.com/rajgoel/reveal.js-plugins/tree/master/chart
- http://bl.ocks.org/mbostock/4060606
- http://www.chartjs.org/
- https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware
- https://github.com/rajgoel/reveal.js-plugins/tree/master/chart
