### ISSUE TITLE
Fetch Data from Google Sheets

### ISSUE THREAD

**Issue by margauxbais** [KpitaineSoftware/kpitaine#3]
Client (manager)
Importer mes données dans Kpitaine depuis Google Sheet
Choisir l'affichage des données

- [ ] Pouvoir choisir quel onglet correspondra à la création d'un graphique dans l'app
- [ ] todo
- [ ] todo
- [ ] todo

**Comment by npracht** [comment]
Possibilité d'exporter les infos sur spreadsheet par API : https://developers.google.com/google-apps/spreadsheets/
